version: "3.8"
services:
  scout:
    build: .
    container_name: scout.agent
    image: scout:latest
    ports:
      - "18081:8080"

  prometheus:
    container_name: scout.prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    container_name: scout.grafana
    image: grafana/grafana-enterprise:8.1.5
    ports:
      - "3000:3000"
    volumes:
      - ".grafana:/var/lib/grafana"